[build]
  # Build command for Next.js
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin will handle routing automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for better security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"
